spring:
  datasource:
    url: jdbc:mysql://43.138.64.174:3306/what_to_eat
    username: DB_root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080
  servlet:
    context-path: /